-- =============================================================================
-- SEED: MOVIES CATALOG (248 FILMS)
-- Includes Hindi, Marathi, and Gujarati films across 80s / 90s / 2000s eras.
-- Run in Supabase SQL Editor after running migrations.
-- =============================================================================

INSERT INTO movies (id, title, year, era, difficulty, language, actors) VALUES
(md5('1-Karz-1980')::uuid, 'Karz', 1980, '80s', 'medium', 'Hindi', ARRAY['Rishi Kapoor', 'Tina Munim']),
(md5('2-Qurbani-1980')::uuid, 'Qurbani', 1980, '80s', 'easy', 'Hindi', ARRAY['Feroz Khan', 'Vinod Khanna', 'Zeenat Aman']),
(md5('3-Shaan-1980')::uuid, 'Shaan', 1980, '80s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Shashi Kapoor', 'Shatrughan Sinha']),
(md5('4-Silsila-1981')::uuid, 'Silsila', 1981, '80s', 'medium', 'Hindi', ARRAY['Amitabh Bachchan', 'Jaya Bachchan', 'Rekha']),
(md5('5-Umrao Jaan-1981')::uuid, 'Umrao Jaan', 1981, '80s', 'medium', 'Hindi', ARRAY['Rekha', 'Farooq Shaikh', 'Naseeruddin Shah']),
(md5('6-Namak Halaal-1982')::uuid, 'Namak Halaal', 1982, '80s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Shashi Kapoor', 'Smita Patil']),
(md5('7-Angoor-1982')::uuid, 'Angoor', 1982, '80s', 'hard', 'Hindi', ARRAY['Sanjeev Kumar', 'Deven Verma', 'Moushumi Chatterjee']),
(md5('8-Disco Dancer-1982')::uuid, 'Disco Dancer', 1982, '80s', 'easy', 'Hindi', ARRAY['Mithun Chakraborty', 'Kim', 'Kalpana Iyer']),
(md5('9-Jaane Bhi Do Yaaro-1983')::uuid, 'Jaane Bhi Do Yaaro', 1983, '80s', 'hard', 'Hindi', ARRAY['Naseeruddin Shah', 'Ravi Baswani', 'Om Puri']),
(md5('10-Himmatwala-1983')::uuid, 'Himmatwala', 1983, '80s', 'medium', 'Hindi', ARRAY['Jeetendra', 'Sridevi']),
(md5('11-Coolie-1983')::uuid, 'Coolie', 1983, '80s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Rishi Kapoor', 'Rati Agnihotri']),
(md5('12-Masoom-1983')::uuid, 'Masoom', 1983, '80s', 'easy', 'Hindi', ARRAY['Naseeruddin Shah', 'Shabana Azmi', 'Jugal Hansraj']),
(md5('13-Sadma-1983')::uuid, 'Sadma', 1983, '80s', 'medium', 'Hindi', ARRAY['Kamal Haasan', 'Sridevi']),
(md5('14-Sharaabi-1984')::uuid, 'Sharaabi', 1984, '80s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Jaya Prada', 'Pran']),
(md5('15-Tohfa-1984')::uuid, 'Tohfa', 1984, '80s', 'hard', 'Hindi', ARRAY['Jeetendra', 'Sridevi', 'Jaya Prada']),
(md5('16-Ram Teri Ganga Maili-1985')::uuid, 'Ram Teri Ganga Maili', 1985, '80s', 'hard', 'Hindi', ARRAY['Rajiv Kapoor', 'Mandakini']),
(md5('17-Karma-1986')::uuid, 'Karma', 1986, '80s', 'easy', 'Hindi', ARRAY['Dilip Kumar', 'Nutan', 'Jackie Shroff', 'Anil Kapoor']),
(md5('18-Nagina-1986')::uuid, 'Nagina', 1986, '80s', 'easy', 'Hindi', ARRAY['Rishi Kapoor', 'Sridevi', 'Amrish Puri']),
(md5('19-Chameli Ki Shaadi-1986')::uuid, 'Chameli Ki Shaadi', 1986, '80s', 'hard', 'Hindi', ARRAY['Anil Kapoor', 'Amrita Singh', 'Pankaj Kapur']),
(md5('20-Mr. India-1987')::uuid, 'Mr. India', 1987, '80s', 'easy', 'Hindi', ARRAY['Anil Kapoor', 'Sridevi', 'Amrish Puri']),
(md5('21-Tezaab-1988')::uuid, 'Tezaab', 1988, '80s', 'easy', 'Hindi', ARRAY['Anil Kapoor', 'Madhuri Dixit', 'Anupam Kher']),
(md5('22-Qayamat Se Qayamat Tak-1988')::uuid, 'Qayamat Se Qayamat Tak', 1988, '80s', 'hard', 'Hindi', ARRAY['Aamir Khan', 'Juhi Chawla']),
(md5('23-Khoon Bhari Maang-1988')::uuid, 'Khoon Bhari Maang', 1988, '80s', 'hard', 'Hindi', ARRAY['Rekha', 'Kabir Bedi', 'Sonu Walia']),
(md5('24-Pushpaka Vimana-1987')::uuid, 'Pushpaka Vimana', 1987, '80s', 'hard', 'Hindi', ARRAY['Kamal Haasan', 'Amala', 'Tinu Anand']),
(md5('25-Tridev-1989')::uuid, 'Tridev', 1989, '80s', 'medium', 'Hindi', ARRAY['Sunny Deol', 'Jackie Shroff', 'Naseeruddin Shah']),
(md5('26-Maine Pyar Kiya-1989')::uuid, 'Maine Pyar Kiya', 1989, '80s', 'easy', 'Hindi', ARRAY['Salman Khan', 'Bhagyashree', 'Alok Nath']),
(md5('27-Chandni-1989')::uuid, 'Chandni', 1989, '80s', 'easy', 'Hindi', ARRAY['Rishi Kapoor', 'Sridevi', 'Vinod Khanna']),
(md5('28-Chaalbaaz-1989')::uuid, 'Chaalbaaz', 1989, '80s', 'medium', 'Hindi', ARRAY['Sridevi', 'Sunny Deol', 'Rajinikanth']),
(md5('29-Parinda-1989')::uuid, 'Parinda', 1989, '80s', 'medium', 'Hindi', ARRAY['Jackie Shroff', 'Anil Kapoor', 'Nana Patekar', 'Anupam Kher']),
(md5('30-Guru-1989')::uuid, 'Guru', 1989, '80s', 'hard', 'Hindi', ARRAY['Mithun Chakraborty', 'Sridevi', 'Shakti Kapoor']),
(md5('31-Zulm Ko Jala Doonga-1988')::uuid, 'Zulm Ko Jala Doonga', 1988, '80s', 'hard', 'Hindi', ARRAY['Naseeruddin Shah', 'Kiran Kumar', 'Sreepradha']),
(md5('32-Aag Hi Aag-1987')::uuid, 'Aag Hi Aag', 1987, '80s', 'hard', 'Hindi', ARRAY['Dharmendra', 'Shatrughan Sinha', 'Moushumi Chatterjee', 'Chunky Pandey']),
(md5('33-Paap Ki Duniya-1988')::uuid, 'Paap Ki Duniya', 1988, '80s', 'hard', 'Hindi', ARRAY['Sunny Deol', 'Neelam Kothari', 'Chunky Pandey']),
(md5('34-Ghatak-1996')::uuid, 'Ghatak', 1996, '90s', 'easy', 'Hindi', ARRAY['Sunny Deol', 'Meenakshi Seshadri', 'Danny Denzongpa']),
(md5('35-Ghayal-1990')::uuid, 'Ghayal', 1990, '90s', 'easy', 'Hindi', ARRAY['Sunny Deol', 'Meenakshi Seshadri', 'Raj Babbar']),
(md5('36-Agneepath-1990')::uuid, 'Agneepath', 1990, '90s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Mithun Chakraborty', 'Madhavi']),
(md5('37-Aashiqui-1990')::uuid, 'Aashiqui', 1990, '90s', 'easy', 'Hindi', ARRAY['Rahul Roy', 'Anu Aggarwal', 'Deepak Tijori']),
(md5('38-Saajan-1991')::uuid, 'Saajan', 1991, '90s', 'easy', 'Hindi', ARRAY['Sanjay Dutt', 'Salman Khan', 'Madhuri Dixit']),
(md5('39-Hum-1991')::uuid, 'Hum', 1991, '90s', 'medium', 'Hindi', ARRAY['Amitabh Bachchan', 'Rajinikanth', 'Govinda']),
(md5('40-Jo Jeeta Wohi Sikandar-1992')::uuid, 'Jo Jeeta Wohi Sikandar', 1992, '90s', 'hard', 'Hindi', ARRAY['Aamir Khan', 'Ayesha Jhulka', 'Deepak Tijori']),
(md5('41-Deewana-1992')::uuid, 'Deewana', 1992, '90s', 'easy', 'Hindi', ARRAY['Rishi Kapoor', 'Divya Bharti', 'Shah Rukh Khan']),
(md5('42-Khiladi-1992')::uuid, 'Khiladi', 1992, '90s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Ayesha Jhulka', 'Deepak Tijori']),
(md5('43-Damini-1993')::uuid, 'Damini', 1993, '90s', 'medium', 'Hindi', ARRAY['Meenakshi Seshadri', 'Sunny Deol', 'Rishi Kapoor']),
(md5('44-Baazigar-1993')::uuid, 'Baazigar', 1993, '90s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Kajol', 'Shilpa Shetty']),
(md5('45-Darr-1993')::uuid, 'Darr', 1993, '90s', 'easy', 'Hindi', ARRAY['Sunny Deol', 'Juhi Chawla', 'Shah Rukh Khan']),
(md5('46-Khalnayak-1993')::uuid, 'Khalnayak', 1993, '90s', 'easy', 'Hindi', ARRAY['Sanjay Dutt', 'Madhuri Dixit', 'Jackie Shroff']),
(md5('47-Andaz Apna Apna-1994')::uuid, 'Andaz Apna Apna', 1994, '90s', 'medium', 'Hindi', ARRAY['Aamir Khan', 'Salman Khan', 'Raveena Tandon', 'Karisma Kapoor', 'Paresh Rawal']),
(md5('48-Hum Aapke Hain Koun-1994')::uuid, 'Hum Aapke Hain Koun', 1994, '90s', 'medium', 'Hindi', ARRAY['Salman Khan', 'Madhuri Dixit', 'Mohnish Bahl']),
(md5('49-Mohra-1994')::uuid, 'Mohra', 1994, '90s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Suniel Shetty', 'Raveena Tandon', 'Paresh Rawal']),
(md5('50-Dilwale Dulhania Le Jayenge-1995')::uuid, 'Dilwale Dulhania Le Jayenge', 1995, '90s', 'hard', 'Hindi', ARRAY['Shah Rukh Khan', 'Kajol', 'Amrish Puri', 'Anupam Kher']),
(md5('51-Karan Arjun-1995')::uuid, 'Karan Arjun', 1995, '90s', 'easy', 'Hindi', ARRAY['Salman Khan', 'Shah Rukh Khan', 'Rakhee', 'Kajol', 'Mamta Kulkarni']),
(md5('52-Rangeela-1995')::uuid, 'Rangeela', 1995, '90s', 'medium', 'Hindi', ARRAY['Aamir Khan', 'Urmila Matondkar', 'Jackie Shroff']),
(md5('53-Coolie No. 1-1995')::uuid, 'Coolie No. 1', 1995, '90s', 'easy', 'Hindi', ARRAY['Govinda', 'Karisma Kapoor', 'Kader Khan']),
(md5('54-Raja Hindustani-1996')::uuid, 'Raja Hindustani', 1996, '90s', 'medium', 'Hindi', ARRAY['Aamir Khan', 'Karisma Kapoor']),
(md5('55-Border-1997')::uuid, 'Border', 1997, '90s', 'easy', 'Hindi', ARRAY['Sunny Deol', 'Suniel Shetty', 'Akshaye Khanna', 'Jackie Shroff']),
(md5('56-Dil To Pagal Hai-1997')::uuid, 'Dil To Pagal Hai', 1997, '90s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Madhuri Dixit', 'Karisma Kapoor', 'Akshay Kumar']),
(md5('57-Gupt-1997')::uuid, 'Gupt', 1997, '90s', 'medium', 'Hindi', ARRAY['Bobby Deol', 'Manisha Koirala', 'Kajol', 'Paresh Rawal']),
(md5('58-Judaai-1997')::uuid, 'Judaai', 1997, '90s', 'hard', 'Hindi', ARRAY['Anil Kapoor', 'Sridevi', 'Urmila Matondkar', 'Paresh Rawal']),
(md5('59-Kuch Kuch Hota Hai-1998')::uuid, 'Kuch Kuch Hota Hai', 1998, '90s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Kajol', 'Rani Mukerji', 'Salman Khan', 'Anupam Kher']),
(md5('60-Satya-1998')::uuid, 'Satya', 1998, '90s', 'easy', 'Hindi', ARRAY['J. D. Chakravarthy', 'Manoj Bajpayee', 'Urmila Matondkar', 'Paresh Rawal']),
(md5('61-Bade Miyan Chote Miyan-1998')::uuid, 'Bade Miyan Chote Miyan', 1998, '90s', 'hard', 'Hindi', ARRAY['Amitabh Bachchan', 'Govinda', 'Raveena Tandon', 'Anupam Kher', 'Paresh Rawal']),
(md5('62-Sarfarosh-1999')::uuid, 'Sarfarosh', 1999, '90s', 'medium', 'Hindi', ARRAY['Aamir Khan', 'Naseeruddin Shah', 'Sonali Bendre']),
(md5('63-Hum Dil De Chuke Sanam-1999')::uuid, 'Hum Dil De Chuke Sanam', 1999, '90s', 'hard', 'Hindi', ARRAY['Salman Khan', 'Aishwarya Rai', 'Ajay Devgn']),
(md5('64-Taal-1999')::uuid, 'Taal', 1999, '90s', 'easy', 'Hindi', ARRAY['Anil Kapoor', 'Aishwarya Rai', 'Akshaye Khanna']),
(md5('65-Vaastav-1999')::uuid, 'Vaastav', 1999, '90s', 'medium', 'Hindi', ARRAY['Sanjay Dutt', 'Namrata Shirodkar', 'Paresh Rawal']),
(md5('66-Biwi No. 1-1999')::uuid, 'Biwi No. 1', 1999, '90s', 'easy', 'Hindi', ARRAY['Salman Khan', 'Karisma Kapoor', 'Sushmita Sen', 'Anil Kapoor']),
(md5('67-Sooryavansham-1999')::uuid, 'Sooryavansham', 1999, '90s', 'medium', 'Hindi', ARRAY['Amitabh Bachchan', 'Jayasudha', 'Soundarya', 'Anupam Kher']),
(md5('68-Gunda-1998')::uuid, 'Gunda', 1998, '90s', 'hard', 'Hindi', ARRAY['Mithun Chakraborty', 'Mukesh Rishi', 'Shakti Kapoor']),
(md5('69-Kaho Naa Pyaar Hai-2000')::uuid, 'Kaho Naa Pyaar Hai', 2000, '2000s', 'hard', 'Hindi', ARRAY['Hrithik Roshan', 'Ameesha Patel', 'Anupam Kher']),
(md5('70-Hera Pheri-2000')::uuid, 'Hera Pheri', 2000, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Suniel Shetty', 'Paresh Rawal']),
(md5('71-Mohabbatein-2000')::uuid, 'Mohabbatein', 2000, '2000s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Shah Rukh Khan', 'Aishwarya Rai', 'Anupam Kher']),
(md5('72-Dhadkan-2000')::uuid, 'Dhadkan', 2000, '2000s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Suniel Shetty', 'Shilpa Shetty']),
(md5('73-Lagaan-2001')::uuid, 'Lagaan', 2001, '2000s', 'easy', 'Hindi', ARRAY['Aamir Khan', 'Gracy Singh', 'Rachel Shelley']),
(md5('74-Dil Chahta Hai-2001')::uuid, 'Dil Chahta Hai', 2001, '2000s', 'medium', 'Hindi', ARRAY['Aamir Khan', 'Saif Ali Khan', 'Akshaye Khanna', 'Preity Zinta']),
(md5('75-Kabhi Khushi Kabhie Gham-2001')::uuid, 'Kabhi Khushi Kabhie Gham', 2001, '2000s', 'hard', 'Hindi', ARRAY['Amitabh Bachchan', 'Shah Rukh Khan', 'Kajol', 'Hrithik Roshan', 'Kareena Kapoor']),
(md5('76-Gadar Ek Prem Katha-2001')::uuid, 'Gadar Ek Prem Katha', 2001, '2000s', 'medium', 'Hindi', ARRAY['Sunny Deol', 'Ameesha Patel', 'Amrish Puri']),
(md5('77-Devdas-2002')::uuid, 'Devdas', 2002, '2000s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Aishwarya Rai', 'Madhuri Dixit']),
(md5('78-Company-2002')::uuid, 'Company', 2002, '2000s', 'medium', 'Hindi', ARRAY['Ajay Devgn', 'Vivek Oberoi', 'Mohanlal', 'Manisha Koirala']),
(md5('79-Saathiya-2002')::uuid, 'Saathiya', 2002, '2000s', 'medium', 'Hindi', ARRAY['Vivek Oberoi', 'Rani Mukerji', 'Shah Rukh Khan']),
(md5('80-Munna Bhai M.B.B.S.-2003')::uuid, 'Munna Bhai M.B.B.S.', 2003, '2000s', 'easy', 'Hindi', ARRAY['Sanjay Dutt', 'Arshad Warsi', 'Boman Irani']),
(md5('81-Kal Ho Naa Ho-2003')::uuid, 'Kal Ho Naa Ho', 2003, '2000s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Saif Ali Khan', 'Preity Zinta']),
(md5('82-Koi Mil Gaya-2003')::uuid, 'Koi Mil Gaya', 2003, '2000s', 'easy', 'Hindi', ARRAY['Hrithik Roshan', 'Preity Zinta', 'Rekha']),
(md5('83-Main Hoon Na-2004')::uuid, 'Main Hoon Na', 2004, '2000s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Suniel Shetty', 'Sushmita Sen', 'Zayed Khan']),
(md5('84-Veer-Zaara-2004')::uuid, 'Veer-Zaara', 2004, '2000s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Preity Zinta', 'Rani Mukerji', 'Anupam Kher']),
(md5('85-Swades-2004')::uuid, 'Swades', 2004, '2000s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Gayatri Joshi', 'Kishori Ballal']),
(md5('86-Dhoom-2004')::uuid, 'Dhoom', 2004, '2000s', 'easy', 'Hindi', ARRAY['Abhishek Bachchan', 'John Abraham', 'Uday Chopra', 'Esha Deol']),
(md5('87-Black-2005')::uuid, 'Black', 2005, '2000s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Rani Mukerji', 'Ayesha Kapur']),
(md5('88-Bunty Aur Babli-2005')::uuid, 'Bunty Aur Babli', 2005, '2000s', 'medium', 'Hindi', ARRAY['Abhishek Bachchan', 'Rani Mukerji', 'Amitabh Bachchan']),
(md5('89-Rang De Basanti-2006')::uuid, 'Rang De Basanti', 2006, '2000s', 'medium', 'Hindi', ARRAY['Aamir Khan', 'Siddharth', 'Sharman Joshi', 'Kunal Kapoor', 'Anupam Kher']),
(md5('90-Omkara-2006')::uuid, 'Omkara', 2006, '2000s', 'medium', 'Hindi', ARRAY['Ajay Devgn', 'Saif Ali Khan', 'Kareena Kapoor', 'Vivek Oberoi']),
(md5('91-Lage Raho Munna Bhai-2006')::uuid, 'Lage Raho Munna Bhai', 2006, '2000s', 'medium', 'Hindi', ARRAY['Sanjay Dutt', 'Arshad Warsi', 'Vidya Balan', 'Boman Irani']),
(md5('92-Chak De India-2007')::uuid, 'Chak De India', 2007, '2000s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Vidya Malvade', 'Sagarika Ghatge']),
(md5('93-Taare Zameen Par-2007')::uuid, 'Taare Zameen Par', 2007, '2000s', 'medium', 'Hindi', ARRAY['Darsheel Safary', 'Aamir Khan', 'Tisca Chopra']),
(md5('94-Jab We Met-2007')::uuid, 'Jab We Met', 2007, '2000s', 'easy', 'Hindi', ARRAY['Shahid Kapoor', 'Kareena Kapoor']),
(md5('95-Om Shanti Om-2007')::uuid, 'Om Shanti Om', 2007, '2000s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Deepika Padukone', 'Arjun Rampal']),
(md5('96-Welcome-2007')::uuid, 'Welcome', 2007, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Nana Patekar', 'Anil Kapoor', 'Paresh Rawal', 'Katrina Kaif']),
(md5('97-Ghajini-2008')::uuid, 'Ghajini', 2008, '2000s', 'easy', 'Hindi', ARRAY['Aamir Khan', 'Asin', 'Jiah Khan']),
(md5('98-Rock On-2008')::uuid, 'Rock On', 2008, '2000s', 'easy', 'Hindi', ARRAY['Farhan Akhtar', 'Arjun Rampal', 'Luke Kenny', 'Purab Kohli']),
(md5('99-Dev.D-2009')::uuid, 'Dev.D', 2009, '2000s', 'medium', 'Hindi', ARRAY['Abhay Deol', 'Mahie Gill', 'Kalki Koechlin']),
(md5('100-3 Idiots-2009')::uuid, '3 Idiots', 2009, '2000s', 'easy', 'Hindi', ARRAY['Aamir Khan', 'R. Madhavan', 'Sharman Joshi', 'Kareena Kapoor', 'Boman Irani']),
(md5('101-Matru Ki Bijlee Ka Mandola-2013')::uuid, 'Matru Ki Bijlee Ka Mandola', 2013, '2000s', 'hard', 'Hindi', ARRAY['Imran Khan', 'Anushka Sharma', 'Pankaj Kapur']),
(md5('102-Suryavanshi-1992')::uuid, 'Suryavanshi', 1992, '90s', 'hard', 'Hindi', ARRAY['Salman Khan', 'Sheeba', 'Saeed Jaffrey']),
(md5('103-Albert Pinto Ko Gussa Kyoon Aata Hai-1980')::uuid, 'Albert Pinto Ko Gussa Kyoon Aata Hai', 1980, '80s', 'hard', 'Hindi', ARRAY['Naseeruddin Shah', 'Shabana Azmi', 'Smita Patil']),
(md5('104-Salim Langde Pe Mat Ro-1989')::uuid, 'Salim Langde Pe Mat Ro', 1989, '80s', 'hard', 'Hindi', ARRAY['Pavan Malhotra', 'Makrand Deshpande', 'Ashutosh Gowariker']),
(md5('105-Saaransh-1984')::uuid, 'Saaransh', 1984, '80s', 'medium', 'Hindi', ARRAY['Anupam Kher', 'Rohini Hattangadi', 'Soni Razdan']),
(md5('106-Daddy-1989')::uuid, 'Daddy', 1989, '80s', 'medium', 'Hindi', ARRAY['Anupam Kher', 'Pooja Bhatt', 'Soni Razdan']),
(md5('107-Ram Lakhan-1989')::uuid, 'Ram Lakhan', 1989, '80s', 'easy', 'Hindi', ARRAY['Anil Kapoor', 'Jackie Shroff', 'Anupam Kher', 'Paresh Rawal']),
(md5('108-Kabzaa-1988')::uuid, 'Kabzaa', 1988, '80s', 'hard', 'Hindi', ARRAY['Sanjay Dutt', 'Amrita Singh', 'Paresh Rawal', 'Anupam Kher']),
(md5('109-Saugandh-1991')::uuid, 'Saugandh', 1991, '90s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Shantipriya', 'Raakhee']),
(md5('110-Khiladiyon Ka Khiladi-1996')::uuid, 'Khiladiyon Ka Khiladi', 1996, '90s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Raveena Tandon', 'Rekha']),
(md5('111-Sabse Bada Khiladi-1995')::uuid, 'Sabse Bada Khiladi', 1995, '90s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Mamta Kulkarni', 'Mohnish Bahl']),
(md5('112-Main Khiladi Tu Anari-1994')::uuid, 'Main Khiladi Tu Anari', 1994, '90s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Saif Ali Khan', 'Shilpa Shetty']),
(md5('113-Mr. and Mrs. Khiladi-1997')::uuid, 'Mr. and Mrs. Khiladi', 1997, '90s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Juhi Chawla', 'Paresh Rawal']),
(md5('114-International Khiladi-1999')::uuid, 'International Khiladi', 1999, '90s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Twinkle Khanna', 'Rajat Bedi']),
(md5('115-Sangharsh-1999')::uuid, 'Sangharsh', 1999, '90s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Preity Zinta', 'Ashutosh Rana']),
(md5('116-Aflatoon-1997')::uuid, 'Aflatoon', 1997, '90s', 'hard', 'Hindi', ARRAY['Akshay Kumar', 'Urmila Matondkar', 'Anupam Kher']),
(md5('117-Deewana Mastana-1997')::uuid, 'Deewana Mastana', 1997, '90s', 'medium', 'Hindi', ARRAY['Anil Kapoor', 'Govinda', 'Juhi Chawla', 'Anupam Kher', 'Salman Khan']),
(md5('118-Chamatkar-1992')::uuid, 'Chamatkar', 1992, '90s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Naseeruddin Shah', 'Urmila Matondkar']),
(md5('119-Raju Ban Gaya Gentleman-1992')::uuid, 'Raju Ban Gaya Gentleman', 1992, '90s', 'hard', 'Hindi', ARRAY['Shah Rukh Khan', 'Juhi Chawla', 'Nana Patekar', 'Amrita Singh']),
(md5('120-Kabhi Haan Kabhi Naa-1994')::uuid, 'Kabhi Haan Kabhi Naa', 1994, '90s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Suchitra Krishnamoorthi', 'Deepak Tijori', 'Paresh Rawal']),
(md5('121-Anjaam-1994')::uuid, 'Anjaam', 1994, '90s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Madhuri Dixit', 'Deepak Tijori']),
(md5('122-Yes Boss-1997')::uuid, 'Yes Boss', 1997, '90s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Juhi Chawla', 'Aditya Pancholi']),
(md5('123-Duplicate-1998')::uuid, 'Duplicate', 1998, '90s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Juhi Chawla', 'Sonali Bendre', 'Anupam Kher']),
(md5('124-Baadshah-1999')::uuid, 'Baadshah', 1999, '90s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Twinkle Khanna', 'Johnny Lever']),
(md5('125-Sanam Bewafa-1991')::uuid, 'Sanam Bewafa', 1991, '90s', 'medium', 'Hindi', ARRAY['Salman Khan', 'Chandni', 'Danny Denzongpa']),
(md5('126-Judwaa-1997')::uuid, 'Judwaa', 1997, '90s', 'easy', 'Hindi', ARRAY['Salman Khan', 'Karisma Kapoor', 'Rambha', 'Anupam Kher']),
(md5('127-Pyaar Kiya To Darna Kya-1998')::uuid, 'Pyaar Kiya To Darna Kya', 1998, '90s', 'hard', 'Hindi', ARRAY['Salman Khan', 'Kajol', 'Arbaaz Khan', 'Anupam Kher']),
(md5('128-Hum Saath Saath Hain-1999')::uuid, 'Hum Saath Saath Hain', 1999, '90s', 'medium', 'Hindi', ARRAY['Salman Khan', 'Saif Ali Khan', 'Mohnish Bahl', 'Tabu', 'Anupam Kher']),
(md5('129-Hello Brother-1999')::uuid, 'Hello Brother', 1999, '90s', 'easy', 'Hindi', ARRAY['Salman Khan', 'Rani Mukerji', 'Arbaaz Khan']),
(md5('130-Sir-1993')::uuid, 'Sir', 1993, '90s', 'hard', 'Hindi', ARRAY['Naseeruddin Shah', 'Pooja Bhatt', 'Atul Agnihotri', 'Paresh Rawal', 'Anupam Kher']),
(md5('131-Woh Chokri-1994')::uuid, 'Woh Chokri', 1994, '90s', 'hard', 'Hindi', ARRAY['Pallavi Joshi', 'Neena Gupta', 'Paresh Rawal']),
(md5('132-Chachi 420-1997')::uuid, 'Chachi 420', 1997, '90s', 'easy', 'Hindi', ARRAY['Kamal Haasan', 'Tabu', 'Amrish Puri', 'Paresh Rawal']),
(md5('133-Tamanna-1997')::uuid, 'Tamanna', 1997, '90s', 'hard', 'Hindi', ARRAY['Paresh Rawal', 'Pooja Bhatt', 'Sharad Kapoor']),
(md5('134-Ajnabee-2001')::uuid, 'Ajnabee', 2001, '2000s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Bobby Deol', 'Kareena Kapoor', 'Bipasha Basu']),
(md5('135-Aankhen-2002')::uuid, 'Aankhen', 2002, '2000s', 'easy', 'Hindi', ARRAY['Amitabh Bachchan', 'Akshay Kumar', 'Sushmita Sen', 'Arjun Rampal', 'Paresh Rawal']),
(md5('136-Awara Paagal Deewana-2002')::uuid, 'Awara Paagal Deewana', 2002, '2000s', 'hard', 'Hindi', ARRAY['Akshay Kumar', 'Suniel Shetty', 'Aftab Shivdasani', 'Paresh Rawal']),
(md5('137-Mujhse Shaadi Karogi-2004')::uuid, 'Mujhse Shaadi Karogi', 2004, '2000s', 'medium', 'Hindi', ARRAY['Salman Khan', 'Akshay Kumar', 'Priyanka Chopra']),
(md5('138-Garam Masala-2005')::uuid, 'Garam Masala', 2005, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'John Abraham', 'Paresh Rawal']),
(md5('139-Phir Hera Pheri-2006')::uuid, 'Phir Hera Pheri', 2006, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Suniel Shetty', 'Paresh Rawal', 'Bipasha Basu']),
(md5('140-Bhool Bhulaiyaa-2007')::uuid, 'Bhool Bhulaiyaa', 2007, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Vidya Balan', 'Shiney Ahuja', 'Paresh Rawal']),
(md5('141-Singh Is Kinng-2008')::uuid, 'Singh Is Kinng', 2008, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Katrina Kaif', 'Om Puri']),
(md5('142-Jaan-E-Mann-2006')::uuid, 'Jaan-E-Mann', 2006, '2000s', 'medium', 'Hindi', ARRAY['Salman Khan', 'Akshay Kumar', 'Preity Zinta', 'Anupam Kher']),
(md5('143-Tere Naam-2003')::uuid, 'Tere Naam', 2003, '2000s', 'easy', 'Hindi', ARRAY['Salman Khan', 'Bhumika Chawla']),
(md5('144-Wanted-2009')::uuid, 'Wanted', 2009, '2000s', 'easy', 'Hindi', ARRAY['Salman Khan', 'Ayesha Takia', 'Prakash Raj']),
(md5('145-Partner-2007')::uuid, 'Partner', 2007, '2000s', 'easy', 'Hindi', ARRAY['Govinda', 'Salman Khan', 'Lara Dutta', 'Katrina Kaif']),
(md5('146-Paheli-2005')::uuid, 'Paheli', 2005, '2000s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Rani Mukerji', 'Anupam Kher']),
(md5('147-Rab Ne Bana Di Jodi-2008')::uuid, 'Rab Ne Bana Di Jodi', 2008, '2000s', 'hard', 'Hindi', ARRAY['Shah Rukh Khan', 'Anushka Sharma']),
(md5('148-A Wednesday!-2008')::uuid, 'A Wednesday!', 2008, '2000s', 'medium', 'Hindi', ARRAY['Naseeruddin Shah', 'Anupam Kher', 'Jimmy Sheirgill']),
(md5('149-Khosla Ka Ghosla-2006')::uuid, 'Khosla Ka Ghosla', 2006, '2000s', 'hard', 'Hindi', ARRAY['Anupam Kher', 'Boman Irani', 'Parvin Dabas']),
(md5('150-Balwaan-1992')::uuid, 'Balwaan', 1992, '90s', 'medium', 'Hindi', ARRAY['Suniel Shetty', 'Divya Bharti', 'Danny Denzongpa']),
(md5('151-Waqt Hamara Hai-1993')::uuid, 'Waqt Hamara Hai', 1993, '90s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Suniel Shetty', 'Ayesha Jhulka']),
(md5('152-Dilwale-1994')::uuid, 'Dilwale', 1994, '90s', 'easy', 'Hindi', ARRAY['Ajay Devgn', 'Suniel Shetty', 'Raveena Tandon']),
(md5('153-Gopi Kishan-1994')::uuid, 'Gopi Kishan', 1994, '90s', 'easy', 'Hindi', ARRAY['Suniel Shetty', 'Karishma Kapoor', 'Shilpa Shirodkar']),
(md5('154-Anth-1994')::uuid, 'Anth', 1994, '90s', 'hard', 'Hindi', ARRAY['Suniel Shetty', 'Somy Ali', 'Paresh Rawal']),
(md5('155-Surakshaa-1995')::uuid, 'Surakshaa', 1995, '90s', 'hard', 'Hindi', ARRAY['Suniel Shetty', 'Saif Ali Khan', 'Sheeba']),
(md5('156-Bhai-1997')::uuid, 'Bhai', 1997, '90s', 'medium', 'Hindi', ARRAY['Suniel Shetty', 'Pooja Batra', 'Sonali Bendre']),
(md5('157-Qayamat: City Under Threat-2003')::uuid, 'Qayamat: City Under Threat', 2003, '2000s', 'hard', 'Hindi', ARRAY['Ajay Devgn', 'Suniel Shetty', 'Sanjay Kapoor']),
(md5('158-De Dana Dan-2009')::uuid, 'De Dana Dan', 2009, '2000s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Suniel Shetty', 'Katrina Kaif', 'Paresh Rawal']),
(md5('159-Ankush-1986')::uuid, 'Ankush', 1986, '80s', 'hard', 'Hindi', ARRAY['Nana Patekar', 'Nisha Singh', 'Raja Bundela']),
(md5('160-Prhaar: The Final Attack-1991')::uuid, 'Prhaar: The Final Attack', 1991, '90s', 'hard', 'Hindi', ARRAY['Nana Patekar', 'Madhuri Dixit', 'Dimple Kapadia']),
(md5('161-Tirangaa-1993')::uuid, 'Tirangaa', 1993, '90s', 'easy', 'Hindi', ARRAY['Raaj Kumar', 'Nana Patekar', 'Mamta Kulkarni']),
(md5('162-Krantiveer-1994')::uuid, 'Krantiveer', 1994, '90s', 'easy', 'Hindi', ARRAY['Nana Patekar', 'Dimple Kapadia', 'Atul Agnihotri', 'Paresh Rawal']),
(md5('163-Agni Sakshi-1996')::uuid, 'Agni Sakshi', 1996, '90s', 'medium', 'Hindi', ARRAY['Jackie Shroff', 'Nana Patekar', 'Manisha Koirala']),
(md5('164-Ghulam-E-Mustafa-1997')::uuid, 'Ghulam-E-Mustafa', 1997, '90s', 'hard', 'Hindi', ARRAY['Nana Patekar', 'Raveena Tandon', 'Paresh Rawal']),
(md5('165-Wajood-1998')::uuid, 'Wajood', 1998, '90s', 'hard', 'Hindi', ARRAY['Nana Patekar', 'Madhuri Dixit', 'Mukul Dev']),
(md5('166-Kohram-1999')::uuid, 'Kohram', 1999, '90s', 'hard', 'Hindi', ARRAY['Amitabh Bachchan', 'Nana Patekar', 'Tabu']),
(md5('167-Ab Tak Chhappan-2004')::uuid, 'Ab Tak Chhappan', 2004, '2000s', 'medium', 'Hindi', ARRAY['Nana Patekar', 'Revathi', 'Yashpal Sharma']),
(md5('168-Bluffmaster!-2005')::uuid, 'Bluffmaster!', 2005, '2000s', 'medium', 'Hindi', ARRAY['Abhishek Bachchan', 'Priyanka Chopra', 'Riteish Deshmukh', 'Nana Patekar']),
(md5('169-Taxi No. 9 2 11-2006')::uuid, 'Taxi No. 9 2 11', 2006, '2000s', 'medium', 'Hindi', ARRAY['Nana Patekar', 'John Abraham', 'Sameera Reddy']),
(md5('170-Mashaal-1984')::uuid, 'Mashaal', 1984, '80s', 'hard', 'Hindi', ARRAY['Dilip Kumar', 'Anil Kapoor', 'Waheeda Rehman', 'Rati Agnihotri']),
(md5('171-Meri Jung-1985')::uuid, 'Meri Jung', 1985, '80s', 'easy', 'Hindi', ARRAY['Anil Kapoor', 'Meenakshi Seshadri', 'Amrish Puri']),
(md5('172-Beta-1992')::uuid, 'Beta', 1992, '90s', 'medium', 'Hindi', ARRAY['Anil Kapoor', 'Madhuri Dixit', 'Aruna Irani', 'Anupam Kher']),
(md5('173-1942: A Love Story-1994')::uuid, '1942: A Love Story', 1994, '90s', 'hard', 'Hindi', ARRAY['Anil Kapoor', 'Manisha Koirala', 'Jackie Shroff', 'Anupam Kher']),
(md5('174-Virasat-1997')::uuid, 'Virasat', 1997, '90s', 'medium', 'Hindi', ARRAY['Anil Kapoor', 'Tabu', 'Pooja Batra', 'Amrish Puri']),
(md5('175-Nayak: The Real Hero-2001')::uuid, 'Nayak: The Real Hero', 2001, '2000s', 'easy', 'Hindi', ARRAY['Anil Kapoor', 'Rani Mukerji', 'Amrish Puri', 'Paresh Rawal']),
(md5('176-C Kkompany-2008')::uuid, 'C Kkompany', 2008, '2000s', 'hard', 'Hindi', ARRAY['Tusshar Kapoor', 'Rajpal Yadav', 'Anupam Kher', 'Raimi Sen']),
(md5('177-Dhol-2007')::uuid, 'Dhol', 2007, '2000s', 'medium', 'Hindi', ARRAY['Sharman Joshi', 'Tusshar Kapoor', 'Kunal Khemu', 'Rajpal Yadav', 'Tanushree Dutta']),
(md5('178-Thanedaar-1990')::uuid, 'Thanedaar', 1990, '90s', 'medium', 'Hindi', ARRAY['Jeetendra', 'Sanjay Dutt', 'Jaya Prada', 'Madhuri Dixit']),
(md5('179-Tejaa-1990')::uuid, 'Tejaa', 1990, '90s', 'hard', 'Hindi', ARRAY['Sanjay Dutt', 'Kimi Katkar', 'Sonu Walia']),
(md5('180-Saudagar-1991')::uuid, 'Saudagar', 1991, '90s', 'medium', 'Hindi', ARRAY['Dilip Kumar', 'Raaj Kumar', 'Manisha Koirala', 'Anupam Kher']),
(md5('181-Taqdeerwala-1995')::uuid, 'Taqdeerwala', 1995, '90s', 'medium', 'Hindi', ARRAY['Venkatesh', 'Raveena Tandon', 'Kader Khan', 'Asrani']),
(md5('182-Delhi Belly-2011')::uuid, 'Delhi Belly', 2011, '2000s', 'easy', 'Hindi', ARRAY['Imran Khan', 'Vir Das', 'Kunaal Roy Kapur']),
(md5('183-Malamaal Weekly-2006')::uuid, 'Malamaal Weekly', 2006, '2000s', 'easy', 'Hindi', ARRAY['Paresh Rawal', 'Om Puri', 'Riteish Deshmukh', 'Rajpal Yadav']),
(md5('184-Chalo Dilli-2011')::uuid, 'Chalo Dilli', 2011, '2000s', 'medium', 'Hindi', ARRAY['Lara Dutta', 'Vinay Pathak', 'Akshay Kumar']),
(md5('185-Khatta Meetha-2010')::uuid, 'Khatta Meetha', 2010, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Trisha Krishnan', 'Rajpal Yadav', 'Johnny Lever']),
(md5('186-Hungama-2003')::uuid, 'Hungama', 2003, '2000s', 'easy', 'Hindi', ARRAY['Akshaye Khanna', 'Aftab Shivdasani', 'Rimi Sen', 'Paresh Rawal']),
(md5('187-Dhum Dhadaka-1985')::uuid, 'Dhum Dhadaka', 1985, '80s', 'easy', 'Marathi', ARRAY['Ashok Saraf', 'Mahesh Kothare', 'Laxmikant Berde', 'Nivedita Joshi']),
(md5('188-Dhadakebaaz-1990')::uuid, 'Dhadakebaaz', 1990, '90s', 'medium', 'Marathi', ARRAY['Laxmikant Berde', 'Mahesh Kothare', 'Deepak Shirke']),
(md5('189-Hamal De Dhamal-1989')::uuid, 'Hamal De Dhamal', 1989, '80s', 'medium', 'Marathi', ARRAY['Laxmikant Berde', 'Varsha Usgaonkar', 'Nilu Phule']),
(md5('190-Ashi Hi Banwa Banwi-1988')::uuid, 'Ashi Hi Banwa Banwi', 1988, '80s', 'easy', 'Marathi', ARRAY['Ashok Saraf', 'Sachin Pilgaonkar', 'Laxmikant Berde', 'Supriya Pilgaonkar']),
(md5('191-Maza Pati Karodpati-1988')::uuid, 'Maza Pati Karodpati', 1988, '80s', 'medium', 'Marathi', ARRAY['Sachin Pilgaonkar', 'Supriya Pilgaonkar', 'Ashok Saraf']),
(md5('192-Aayatya Gharat Gharoba-1991')::uuid, 'Aayatya Gharat Gharoba', 1991, '90s', 'medium', 'Marathi', ARRAY['Sachin Pilgaonkar', 'Ashok Saraf', 'Supriya Pilgaonkar', 'Laxmikant Berde']),
(md5('193-Aflatoon-1991')::uuid, 'Aflatoon', 1991, '90s', 'hard', 'Marathi', ARRAY['Laxmikant Berde', 'Sudhir Joshi', 'Ashok Saraf']),
(md5('194-Navra Maza Navsacha-2004')::uuid, 'Navra Maza Navsacha', 2004, '2000s', 'easy', 'Marathi', ARRAY['Sachin Pilgaonkar', 'Supriya Pilgaonkar', 'Ashok Saraf', 'Johnny Lever']),
(md5('195-Thartharat-1989')::uuid, 'Thartharat', 1989, '80s', 'hard', 'Marathi', ARRAY['Mahesh Kothare', 'Laxmikant Berde', 'Priya Arun']),
(md5('196-Zapatlela-1993')::uuid, 'Zapatlela', 1993, '90s', 'easy', 'Marathi', ARRAY['Laxmikant Berde', 'Mahesh Kothare', 'Dilip Prabhavalkar']),
(md5('197-Jatra: Hyalagaad Re Tyalagaad-2006')::uuid, 'Jatra: Hyalagaad Re Tyalagaad', 2006, '2000s', 'hard', 'Marathi', ARRAY['Bharat Jadhav', 'Siddharth Jadhav', 'Priya Arun']),
(md5('198-Khabardar-2005')::uuid, 'Khabardar', 2005, '2000s', 'medium', 'Marathi', ARRAY['Bharat Jadhav', 'Sanjay Narvekar', 'Nirmiti Sawant']),
(md5('199-Hulchul-2004')::uuid, 'Hulchul', 2004, '2000s', 'easy', 'Hindi', ARRAY['Akshaye Khanna', 'Kareena Kapoor', 'Paresh Rawal', 'Arshad Warsi']),
(md5('200-Chup Chup Ke-2006')::uuid, 'Chup Chup Ke', 2006, '2000s', 'easy', 'Hindi', ARRAY['Shahid Kapoor', 'Kareena Kapoor', 'Paresh Rawal', 'Rajpal Yadav']),
(md5('201-Bhagam Bhag-2006')::uuid, 'Bhagam Bhag', 2006, '2000s', 'easy', 'Hindi', ARRAY['Akshay Kumar', 'Govinda', 'Paresh Rawal']),
(md5('202-Golmaal: Fun Unlimited-2006')::uuid, 'Golmaal: Fun Unlimited', 2006, '2000s', 'easy', 'Hindi', ARRAY['Ajay Devgn', 'Arshad Warsi', 'Sharman Joshi', 'Tusshar Kapoor', 'Paresh Rawal']),
(md5('203-Dhamaal-2007')::uuid, 'Dhamaal', 2007, '2000s', 'easy', 'Hindi', ARRAY['Sanjay Dutt', 'Riteish Deshmukh', 'Arshad Warsi', 'Javed Jaffrey']),
(md5('204-All the Best: Fun Begins-2009')::uuid, 'All the Best: Fun Begins', 2009, '2000s', 'medium', 'Hindi', ARRAY['Ajay Devgn', 'Sanjay Dutt', 'Fardeen Khan', 'Bipasha Basu']),
(md5('205-One 2 Ka 4-2001')::uuid, 'One 2 Ka 4', 2001, '2000s', 'medium', 'Hindi', ARRAY['Shah Rukh Khan', 'Juhi Chawla', 'Jackie Shroff']),
(md5('206-Badshah-1999')::uuid, 'Badshah', 1999, '90s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Twinkle Khanna', 'Johnny Lever']),
(md5('207-Chalte Chalte-2003')::uuid, 'Chalte Chalte', 2003, '2000s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Rani Mukerji', 'Satish Shah']),
(md5('208-Josh-2000')::uuid, 'Josh', 2000, '2000s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Aishwarya Rai', 'Chandrachur Singh', 'Sharad Kapoor']),
(md5('209-Koyla-1997')::uuid, 'Koyla', 1997, '90s', 'easy', 'Hindi', ARRAY['Shah Rukh Khan', 'Madhuri Dixit', 'Amrish Puri']),
(md5('211-Bandhan-1998')::uuid, 'Bandhan', 1998, '90s', 'medium', 'Hindi', ARRAY['Salman Khan', 'Jackie Shroff', 'Rambha']),
(md5('212-Dulhan Hum Le Jayenge-2000')::uuid, 'Dulhan Hum Le Jayenge', 2000, '2000s', 'medium', 'Hindi', ARRAY['Salman Khan', 'Karisma Kapoor', 'Paresh Rawal', 'Anupam Kher']),
(md5('213-Garv: Pride and Honour-2004')::uuid, 'Garv: Pride and Honour', 2004, '2000s', 'hard', 'Hindi', ARRAY['Salman Khan', 'Shilpa Shetty', 'Amrish Puri']),
(md5('214-Lucky: No Time for Love-2005')::uuid, 'Lucky: No Time for Love', 2005, '2000s', 'hard', 'Hindi', ARRAY['Salman Khan', 'Sneha Ullal', 'Mithun Chakraborty']),
(md5('215-No Entry-2005')::uuid, 'No Entry', 2005, '2000s', 'easy', 'Hindi', ARRAY['Anil Kapoor', 'Salman Khan', 'Fardeen Khan', 'Bipasha Basu']),
(md5('216-Eeshwar-1989')::uuid, 'Eeshwar', 1989, '80s', 'hard', 'Hindi', ARRAY['Anil Kapoor', 'Vijayshanti', 'Saeed Jaffrey']),
(md5('217-Kishen Kanhaiya-1990')::uuid, 'Kishen Kanhaiya', 1990, '90s', 'medium', 'Hindi', ARRAY['Anil Kapoor', 'Madhuri Dixit', 'Shilpa Shirodkar', 'Amrish Puri']),
(md5('218-Khel-1992')::uuid, 'Khel', 1992, '90s', 'medium', 'Hindi', ARRAY['Anil Kapoor', 'Madhuri Dixit', 'Anupam Kher']),
(md5('219-Roop Ki Rani Choron Ka Raja-1993')::uuid, 'Roop Ki Rani Choron Ka Raja', 1993, '90s', 'hard', 'Hindi', ARRAY['Anil Kapoor', 'Sridevi', 'Anupam Kher', 'Paresh Rawal']),
(md5('220-Loafer-1996')::uuid, 'Loafer', 1996, '90s', 'medium', 'Hindi', ARRAY['Anil Kapoor', 'Juhi Chawla', 'Kulbhushan Kharbanda']),
(md5('221-Gharwali Baharwali-1998')::uuid, 'Gharwali Baharwali', 1998, '90s', 'hard', 'Hindi', ARRAY['Anil Kapoor', 'Raveena Tandon', 'Rambha']),
(md5('223-Pukar-2000')::uuid, 'Pukar', 2000, '2000s', 'medium', 'Hindi', ARRAY['Anil Kapoor', 'Madhuri Dixit', 'Danny Denzongpa']),
(md5('224-Armaan-2003')::uuid, 'Armaan', 2003, '2000s', 'medium', 'Hindi', ARRAY['Amitabh Bachchan', 'Anil Kapoor', 'Preity Zinta']),
(md5('225-Race-2008')::uuid, 'Race', 2008, '2000s', 'easy', 'Hindi', ARRAY['Saif Ali Khan', 'Akshaye Khanna', 'Anil Kapoor', 'Bipasha Basu']),
(md5('226-Tashan-2008')::uuid, 'Tashan', 2008, '2000s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Saif Ali Khan', 'Kareena Kapoor', 'Anil Kapoor']),
(md5('228-Andaaz-2003')::uuid, 'Andaaz', 2003, '2000s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Lara Dutta', 'Priyanka Chopra']),
(md5('229-Aitraaz-2004')::uuid, 'Aitraaz', 2004, '2000s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Kareena Kapoor', 'Priyanka Chopra', 'Paresh Rawal']),
(md5('230-Waqt: The Race Against Time-2005')::uuid, 'Waqt: The Race Against Time', 2005, '2000s', 'hard', 'Hindi', ARRAY['Amitabh Bachchan', 'Akshay Kumar', 'Priyanka Chopra', 'Boman Irani']),
(md5('231-Jaanwar-1999')::uuid, 'Jaanwar', 1999, '90s', 'medium', 'Hindi', ARRAY['Akshay Kumar', 'Karisma Kapoor', 'Shilpa Shetty']),
(md5('233-Kaante-2002')::uuid, 'Kaante', 2002, '2000s', 'medium', 'Hindi', ARRAY['Amitabh Bachchan', 'Sanjay Dutt', 'Suniel Shetty', 'Kumar Gaurav']),
(md5('234-LOC Kargil-2003')::uuid, 'LOC Kargil', 2003, '2000s', 'hard', 'Hindi', ARRAY['Sanjay Dutt', 'Ajay Devgn', 'Suniel Shetty', 'Saif Ali Khan']),
(md5('235-Dus-2005')::uuid, 'Dus', 2005, '2000s', 'easy', 'Hindi', ARRAY['Sanjay Dutt', 'Suniel Shetty', 'Abhishek Bachchan', 'Zayed Khan']),
(md5('236-Shootout at Lokhandwala-2007')::uuid, 'Shootout at Lokhandwala', 2007, '2000s', 'hard', 'Hindi', ARRAY['Sanjay Dutt', 'Suniel Shetty', 'Vivek Oberoi', 'Amitabh Bachchan']),
(md5('237-Shikhar-2005')::uuid, 'Shikhar', 2005, '2000s', 'medium', 'Hindi', ARRAY['Ajay Devgn', 'Shahid Kapoor', 'Bipasha Basu', 'John Abraham']),
(md5('238-Apaharan-2005')::uuid, 'Apaharan', 2005, '2000s', 'medium', 'Hindi', ARRAY['Ajay Devgn', 'Bipasha Basu', 'Nana Patekar']),
(md5('239-Yugpurush-1998')::uuid, 'Yugpurush', 1998, '90s', 'hard', 'Hindi', ARRAY['Nana Patekar', 'Jackie Shroff', 'Manisha Koirala']),
(md5('240-Hu Tu Tu-1999')::uuid, 'Hu Tu Tu', 1999, '90s', 'hard', 'Hindi', ARRAY['Nana Patekar', 'Suniel Shetty', 'Tabu']),
(md5('241-Shakti: The Power-2002')::uuid, 'Shakti: The Power', 2002, '2000s', 'medium', 'Hindi', ARRAY['Nana Patekar', 'Karisma Kapoor', 'Sanjay Kapoor', 'Shah Rukh Khan']),
(md5('242-Chaal Jeevi Laiye-2019')::uuid, 'Chaal Jeevi Laiye', 2019, '2000s', 'hard', 'Gujarati', ARRAY['Siddharth Randeria', 'Yash Soni', 'Aarohi Patel']),
(md5('243-Gammat Jammat-1987')::uuid, 'Gammat Jammat', 1987, '80s', 'medium', 'Marathi', ARRAY['Sachin Pilgaonkar', 'Ashok Saraf', 'Varsha Usgaonkar']),
(md5('244-Bhootacha Bhau-1989')::uuid, 'Bhootacha Bhau', 1989, '80s', 'hard', 'Marathi', ARRAY['Ashok Saraf', 'Sachin Pilgaonkar', 'Laxmikant Berde']),
(md5('245-Shejari Shejari-1990')::uuid, 'Shejari Shejari', 1990, '90s', 'hard', 'Marathi', ARRAY['Ashok Saraf', 'Laxmikant Berde', 'Nishigandha Wad']),
(md5('246-Choukat Raja-1991')::uuid, 'Choukat Raja', 1991, '90s', 'hard', 'Marathi', ARRAY['Dilip Prabhavalkar', 'Sulabha Deshpande', 'Ashok Saraf']),
(md5('247-Zapatlela 2-2013')::uuid, 'Zapatlela 2', 2013, '2000s', 'easy', 'Marathi', ARRAY['Adinath Kothare', 'Dilip Prabhavalkar', 'Sonalee Kulkarni']),
(md5('248-Pachadlela-2004')::uuid, 'Pachadlela', 2004, '2000s', 'medium', 'Marathi', ARRAY['Bharat Jadhav', 'Shreyas Talpade', 'Laxmikant Berde', 'Dilip Prabhavalkar']),
(md5('249-De Dhakka-2008')::uuid, 'De Dhakka', 2008, '2000s', 'easy', 'Marathi', ARRAY['Makarand Anaspure', 'Shivaji Satam', 'Siddharth Jadhav']),
(md5('250-Saade Maade Teen-2007')::uuid, 'Saade Maade Teen', 2007, '2000s', 'medium', 'Marathi', ARRAY['Ashok Saraf', 'Bharat Jadhav', 'Makarand Anaspure', 'Siddharth Jadhav']),
(md5('251-Me Shivajiraje Bhosale Boltoy-2009')::uuid, 'Me Shivajiraje Bhosale Boltoy', 2009, '2000s', 'hard', 'Marathi', ARRAY['Mahesh Manjrekar', 'Sachin Khedekar', 'Makarand Anaspure']),
(md5('252-Natrang-2010')::uuid, 'Natrang', 2010, '2000s', 'medium', 'Marathi', ARRAY['Atul Kulkarni', 'Sonalee Kulkarni', 'Kishor Kadam'])
ON CONFLICT (title, year, language) DO UPDATE SET
  era = EXCLUDED.era,
  difficulty = EXCLUDED.difficulty,
  actors = EXCLUDED.actors;
